## ===----------------------------------------------------------------------===##
##
## This source file is part of the SwiftNIO open source project
##
## Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of SwiftNIO project authors
##
## SPDX-License-Identifier: Apache-2.0
##
## ===----------------------------------------------------------------------===##

ignore: |
  Sources/Clibuv/libuv/
  Sources/CDataStaxDriver/datastax-cpp-driver

extends: default

rules:
  line-length: false
  document-start: false
  truthy:
    check-keys: false  # Otherwise we get a false positive on GitHub action's `on` key
